# Generated by Django 2.2.8 on 2021-09-30 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bacnet", "0003_auto_20210930_0956"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bacnetvariableproperty",
            old_name="bacnet_device",
            new_name="bacnet_variable",
        ),
    ]
