# Generated by Django 2.2.8 on 2021-09-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacnet', '0005_add_device_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacnetvariable',
            name='bacnet_device',
        ),
    ]
