# Generated by Django 2.2.8 on 2021-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bacnet", "0008_auto_20211004_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bacnetdevice",
            name="device_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Local"), (1, "Remote")],
                default=0,
                help_text="Set a local bacnet device to discover remote BACNet devices on the network",
            ),
        ),
    ]
