# Generated by Django 2.2.8 on 2021-11-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacnet', '0010_auto_20211004_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bacnetdevice',
            options={'verbose_name': 'BACnet Device', 'verbose_name_plural': 'BACnet Devices'},
        ),
        migrations.AlterModelOptions(
            name='bacnetdeviceproperty',
            options={'verbose_name': 'BACnet Device Property', 'verbose_name_plural': 'BACnet Device Properties'},
        ),
        migrations.AlterModelOptions(
            name='bacnetvariable',
            options={'verbose_name': 'BACnet Variable', 'verbose_name_plural': 'BACnet Variables'},
        ),
        migrations.AlterModelOptions(
            name='bacnetvariableproperty',
            options={'verbose_name': 'BACnet Variable Property', 'verbose_name_plural': 'BACnet Variable Properties'},
        ),
    ]
