# Generated by Django 2.2.8 on 2021-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacnet', '0013_auto_20211206_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacnetdevice',
            name='remote_devices_variables',
            field=models.CharField(default='', help_text='After creating a remote device, refresh the page until you see the result', max_length=2000),
        ),
    ]
