# Generated by Django 2.2.24 on 2022-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacnet', '0014_auto_20211206_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacnetdevice',
            name='remote_devices_discovered',
            field=models.CharField(blank=True, default='', help_text='After creating a local device, refresh the page until you see the result', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bacnetdevice',
            name='remote_devices_variables',
            field=models.CharField(blank=True, default='', help_text='After creating a remote device, refresh the page until you see the result', max_length=2000, null=True),
        ),
    ]
